<?php

acf_add_local_field_group(array(
	'key' => 'group_5ebfd3c6bf333',
	'title' => 'Saber Convert Text',
	'fields' => array(
		array(
			'key' => 'field_5ebfd3d9d5369',
			'label' => 'Text',
			'name' => 'text',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'new_lines' => '',
			'maxlength' => '',
			'placeholder' => '',
			'rows' => '',
		),
		array(
			'key' => 'field_5ec0af94dad5e',
			'label' => 'Voice',
			'name' => 'voice_id',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => $voiceList,
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 'Joanna',
			'layout' => 'horizontal',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5ebfd3e1d536a',
			'label' => 'File Storage',
			'name' => 'file_storage',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				's3' => 'S3 Bucket',
				'server' => 'Server',
			),
			'allow_null' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5ec0a0089b48f',
			'label' => 'Media Library Import',
			'name' => 'media_library_import',
			'type' => 'button_group',
			'instructions' => 'This option will add the speech audio file to the WP Media Library.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				0 => 'No',
				1 => 'Yes',
			),
			'allow_null' => 0,
			'default_value' => 1,
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-convert-text',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));
